---
include:
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.88/workflow-default.yml"
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.88/terraform-toolkit.yml"
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.88/git-toolkit.yml"
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.88/gitlab-toolkit.yml"

get-latest-terraform:
  extends: .get-latest-terraform

check-formatting:
  extends: .check-formatting

validate:
  extends: .validate-terraform
  variables:
    ENVIRONMENTS: examples/complete

miquido-ci-schema-validation:
  extends: .miquido-ci-schema-validation

bump-tag:
  extends: .bump_minor_tag
